export const skils = [
    { id: 1, name: "Html", styles: " " },
    { id: 2, name: "Css", styles: " " },
    { id: 3, name: "Scss", styles: " " },
    { id: 4, name: "Javascript", styles: " " },
    { id: 5, name: "TypeScript", styles: " " },
    { id: 6, name: "React", styles: " " },
    { id: 7, name: "Next.js", styles: " " },
    { id: 8, name: "Tailwind", styles: " " },
    { id: 9, name: "Styled Components", styles: "text-slate-500" },
    { id: 10, name: "Material UI", styles: "" },
    { id: 11, name: "NextUI", styles: "" },
    { id: 12, name: "Redux", styles: "" },
    { id: 13, name: "Redux Toolkit", styles: "" },
    { id: 14, name: "TanStack Query", styles: " " },
    { id: 15, name: "React Hook Form", styles: "" },
    { id: 16, name: "GraphQL", styles: "" },
    { id: 17, name: "Apollo Client", styles: "" },
    { id: 18, name: "DatoCms", styles: "" },
    { id: 19, name: "Git", styles: " " },
    { id: 20, name: "Figma", styles: "" },
    { id: 21, name: "Storybook", styles: "" },
];