export const skils = [
    { id: 1, name: "Html" },
    { id: 2, name: "Css" },
    { id: 3, name: "Scss" },
    { id: 4, name: "Javascript" },
    { id: 5, name: "TypeScript" },
    { id: 6, name: "React" },
    { id: 7, name: "Next.js" },
    { id: 8, name: "Tailwind" },
    { id: 9, name: "Styled Components" },
    { id: 10, name: "Material UI" },
    { id: 11, name: "daisyUI" },
    { id: 12, name: "Redux" },
    { id: 13, name: "Redux Toolkit" },
    { id: 14, name: "TanStack Query" },
    { id: 15, name: "React Hook Form" },
    { id: 16, name: "GraphQL" },
    { id: 17, name: "Apollo Client" },
    { id: 18, name: "DatoCms" },
    { id: 19, name: "Git" },
    { id: 20, name: "Figma" },
    { id: 21, name: "Storybook" },
];
